### ISSUE TITLE
When exporting the Eldon law ring model as a DAE file, there will be a confusion in the surface

### ISSUE THREAD

**Issue by mayloglog** [asasasasasbc/FLVER_Editor#10]
![屏幕截图 2022-03-05 145746](https://user-images.githubusercontent.com/100988988/156872387-58e4ad25-f758-4250-8baa-424daa6e77ff.png)
[c8906.7z.zip](https://github.com/asasasasasbc/FLVER_Editor/files/8190186/c8906.7z.zip)

**Comment by asasasasasbc** [comment]
Mesh的LOD问题，如果有空的话我会尝试修复的
