### ISSUE TITLE
Imported model disappears/fades out when far from the player

### ISSUE THREAD

**Issue by huckleberrypie** [asasasasasbc/FLVER_Editor#3]
Title says all. I've been told that this is due to the LOD facesets not being accounted for when importing using your editor, hence the issue.

I've attached the .DCX files I made as well as screenshots showing the issue in action.
![Sekiro_26_08_2019_9_19_27_PM](https://user-images.githubusercontent.com/5564327/63773353-93075580-c90d-11e9-8ff6-aef6386b67cc.png)
![Sekiro_26_08_2019_9_20_36_PM](https://user-images.githubusercontent.com/5564327/63773392-a5818f00-c90d-11e9-99b4-818ead5c6c6a.png)
[chr.zip](https://github.com/asasasasasbc/FLVER_Editor/files/3546150/chr.zip)

**Comment by huckleberrypie** [comment]
Anyone?

**Comment by asasasasasbc** [comment]
This flver editor was intended to make mods that are not influenced by LOD..
If you want to solve the LOD problem, then you may need to use yabber or something to change the LOD configurations of the game.

You may also do some research of the LOD mechanism, if you can find some clues, please tell me and I can add the related LOD functionality to the editor.

**Comment by asasasasasbc** [comment]
(LOD = level of detail)

**Comment by huckleberrypie** [comment]
> 
> 
> This flver editor was intended to make mods that are not influenced by LOD..
> If you want to solve the LOD problem, then you may need to use yabber or something to change the LOD configurations of the game.
> 
> You may also do some research of the LOD mechanism, if you can find some clues, please tell me and I can add the related LOD functionality to the editor.

I see, though I am not involved with reverse-engineering the file formats lol. If I may recall Meowmaritus and his buddies did document the LOD stuff some time ago. You might want to contact him on Discord about it, if you don't mind that is.
