### ISSUE TITLE
Export fusing models with LOD

### ISSUE THREAD

**Issue by HandelC** [asasasasasbc/FLVER_Editor#5]
When I click Export as a DAE, the model comes as the objects as each, like the bonfire is called "ash" and "sword", but when you look at it, the normal model and the LOD is fused! Not just over each other, but fused, trying to separate in blender with "P> By loose parts" don't separate it and I noticed that even the vertex appear to be merged... (Hope it's not me doing something wrong)

**Comment by asasasasasbc** [comment]
Model exporting is experimental. You can use "BB model extractor(Convert .flver model file to importable XPS file):https://forum.xentax.com/viewtopic.php?f=16&t=17332" to export proper models.
