### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Eraea** [asasasasasbc/FLVER_Editor#9]
Hello, I'm wondering if it is possible for this tool to read an FLVER from a different FromSoft game?
The game is called Kido Senshi Gundam Unicorn and it released on the PS3 six months after the original Dark Souls released.
The game uses the same archive system and file structures (TPF, FLVER, HKX, etc.) but I haven't seen any work done on extracting stuff from this game, along with the Armored Core games.

**Comment by asasasasasbc** [comment]
Sorry, I don't have any plan studying old fromsoftware game's FLVER file, but I will try my best support the latest title Elden Ring's FLVER file.
